name: Deploy Pipeline

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to DEV
        run: |
          xcopy /E /I /Y . C:\deploy\dev

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: self-hosted
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to STAGING
        run: |
          xcopy /E /I /Y . C:\deploy\staging

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to MAIN
        run: |
          xcopy /E /I /Y . C:\deploy\main
